version: "3"
services:
 prauxy:
  build: .
  depends_on:
  - mongo
  - redis
  networks:
    - prauxy-network
 mongo:
  image: "mongo"
  networks:
    - prauxy-network
 redis:
  image: "redis"
  networks:
    - prauxy-network
 server:
  image: nginx:mainline-alpine
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./nginx-conf:/etc/nginx/conf.d
  depends_on:
    - prauxy
  networks:
    - prauxy-network

networks:
  prauxy-network:
    driver: bridge